version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=8.4
        - NODE_VERSION=18
        - INSTALL_BUN=true
        - INSTALL_PNPM=false
    container_name: mario_app
    platform: linux/amd64
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    depends_on:
      - db
      - redis
    networks:
      - mario_network
    restart: unless-stopped
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - PHP_VERSION=8.4
      - NODE_VERSION=18
      - PHP_MEMORY_LIMIT=1024M
    ports:
      - "5173:5173"

  nginx:
    image: nginx:alpine
    container_name: mario_nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - mario_network
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: mario_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mario
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/mysql-client.cnf:/etc/mysql/conf.d/mysql-client.cnf
    networks:
      - mario_network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci


  redis:
    image: redis:7-alpine
    container_name: mario_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mario_network
    restart: unless-stopped
    command: redis-server --appendonly yes





volumes:
  mysql_data:
    driver: local

  redis_data:
    driver: local

networks:
  mario_network:
    driver: bridge
